appConfig:
  spring:
    cloud:
      gateway:
        routes:
          - id: users-roles
            uri: ${users-roles.url}
            predicates:
              - Path=/user-api/mtls/**
            filters:
              - StripPrefix=1

  public-urls:
    - method: GET
      path: "/actuator/**"
  abac:
    - method: POST
      path: "/user-api/mtls/ephemeral-proof"
      disable-ephemeral-proof-check: true
    # Example of ABAC
    # - path: "/this-is-an-example"
    #   method: GET
    #   disable-ephemeral-proof-check: true
    #   identity-attributes:
    #     - CONSUMER
    #     - DATA_PROVIDER
